stages:
  - lint
  - test
  - docker-build-push
  

variables:
  IMAGE_NAME: ihebbennaceur/tinyleaves-fastapi
  IMAGE_TAG: latest

# --------------------------------------
# STAGE: Vérification du code (qualité)
# --------------------------------------

flake8-lint:
  stage: lint
  image: python:3.10
  before_script:
    - pip install flake8
  script:
    - flake8 app/ tests/
  allow_failure: true  # Bloquant si erreurs


# --------------------------------------
# STAGE: Tests
# --------------------------------------

pytest-tests:
  stage: test
  image: python:3.10
  before_script:
    - pip install -r requirements.txt
    - pip install pytest
  script:
    - pytest tests/
  artifacts:
    when: always
    reports:
      junit: pytest-report.xml

# --------------------------------------
# STAGE: Construction de l'image Docker nd push
# --------------------------------------
build & push:
  stage: docker-build-push
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: ""
  before_script:
    - echo "$DOCKER_HUB_PASSWORD" | docker login -u "ihebbennaceur" --password-stdin
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker push $IMAGE_NAME:$IMAGE_TAG
  only:
    - main

